# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2024-12-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataModel.Field')),
            ],
        ),
    ]
